username: "![qJZ6HjZtiC0dpYxmQyJiptOFDxdgDPUIoS0dmu7d6q4=]"
password: "![fQrjowPakZHekUK9xaW3fA==]"
securitytoken: "![KttTugD6Rxthm1JYjOoB6r7P02DbwzovbOc2iP2YMdM=]"


host: "![SxCtFjkZBjCB0rMJWRCnEQ==]"
port: "3306"
user: "freedb_Shyam"
dbpassword: "![MUleiYInMMhVBu12G4DSLQ==]"
database: "freedb_mahesh"